### PR TITLE
React update

### PR DESCRIPTION
**Pull request by mhomolak**

### CODE REVIEW

**Comment by StommePoes** [comment]
Looks good. I thought we were already calling local React dependency, was that in other components and just not Alerts?

**Comment by mhomolak** [comment]
I believe they're in every demo page.

**Comment by umahaea** [comment]
Regression passes, so good from QA. Nothing more to test here.

**Comment by mhomolak** [comment]
I'll just add this in while I'm doing the style updates instead of this separate PR.

**Pull request closed without merging**
